# Generated by Django 4.1.2 on 2023-02-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_ad_user_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='avatar',
        ),
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photo', verbose_name='Аватар'),
        ),
    ]
