# Generated by Django 4.1.2 on 2023-02-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_ad_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'permissions': [('is_staff', 'Модератор')]},
        ),
    ]
